version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fluxo-planejados-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fluxo_erp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: fluxo-planejados-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/fluxo_erp
      ADMIN_EMAIL: ottonsilva@gmail.com
      ADMIN_PASSWORD: "123456"
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fluxo-planejados-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
